Added status bar height package and fixed back button on iOS
language-transfer/lt-app pull request #56
Opened 2022-05-25 23:18 UTC by jafayer

In styles, changed marginTop to paddingTop because the body element did not span the full height of the page and marginTop was leaving a grey bar. This change is untested on other devices.

2022-07-05 20:21 UTC, SyntaxBlitz requested changes

2022-07-08 21:45 UTC, jafayer commented on js/components/Listen/ListenHeader.react.tsx
> +            size={30}
Find out if we need the backbuttoncontainer and if so make it only on iOS. Test on both devices to make sure android is unaffected and behaves normally.

2022-07-14 18:08 UTC, SyntaxBlitz approved these changes

2022-07-14 18:08 UTC, SyntaxBlitz commented on js/components/Listen/ListenHeader.react.tsx
> +        ]}>
I think this needs 2 spaces of un-tab

2022-07-15 00:32 UTC, merged